;;; custom.el --- user customization file    -*- lexical-binding: t no-byte-compile: t -*-
;;; Commentary:
;;;       Add or change the configurations in custom.el, then restart Emacs.
;;;       Put your own configurations in custom-post.el to override default configurations.
;;; Code:

;; The theme is `pinaceae' (themes/pinaceae-theme.el), generated by
;; matugen — reload it with M-x flutter-load-theme or via the toggles hydra.
;; (setq flutter-full-name "user name")           ; User full name
;; (setq flutter-mail-address "user@email.com")   ; Email address
;; (setq flutter-proxy "127.0.0.1:7897")          ; HTTP/HTTPS proxy
;; (setq flutter-socks-proxy "127.0.0.1:7897")    ; SOCKS proxy

;; (setq flutter-use-exec-path-from-shell nil)    ; Use `exec-path-from-shell' or not. If using emacs-plus with path ejection, set to nil
;; (setq flutter-icon nil)                        ; Display icons or not: t or nil
;; (setq flutter-package-archives 'melpa)         ; Package repo: melpa, bfsu, iscas, netease, sjtu, tencent, tuna or ustc
;; (setq flutter-completion-style 'minibuffer)    ; Completion display style: minibuffer or childframe
;; (setq flutter-frame-maximized-on-startup t)    ; Maximize frame on startup or not: t or nil
;; (setq flutter-dashboard nil)                   ; Display dashboard at startup or not: t or nil
;; (setq flutter-lsp nil)                         ; Enable lsp or not: t or nil
;; (setq flutter-tree-sitter nil)                 ; Enable tree-sitter or not: t or nil. Only available in 29+.
;; (setq flutter-chinese-calendar t)              ; Support Chinese calendar or not: t or nil
;; (setq flutter-player t)                        ; Enable players or not: t or nil
(setq flutter-prettify-symbols-alist nil)      ; Alist of symbol prettifications. Nil to use font supports ligatures.

;; For Emacs devel
;; (setq package-user-dir (locate-user-emacs-file (format "elpa-%s" emacs-major-version)))
;; (setq desktop-base-file-name (format ".emacs-%s.desktop" emacs-major-version))
;; (setq desktop-base-lock-name (format ".emacs-%s.desktop.lock" emacs-major-version))

;; Fonts
(defun flutter-setup-fonts ()
  "Setup fonts."
  (when (display-graphic-p)
    ;; Set default font
    (cl-loop for font in '("JetBrainsMono Nerd Font" "FiraCode Nerd Font" "CaskaydiaCove Nerd Font"
                           "Fira Code" "Cascadia Code" "Jetbrains Mono"
                           "SF Mono" "Menlo" "Hack" "Source Code Pro"
                           "Monaco" "DejaVu Sans Mono" "Consolas")
             when (font-available-p font)
             return (set-face-attribute 'default nil
                                        :family font
                                        :height (cond (sys/macp 130)
                                                      (sys/win32p 110)
                                                      (t 100))))

    ;; Set mode-line font
    (cl-loop for font in '("Arial" "Helvetica" "Times New Roman")
             when (font-available-p font)
             return (progn
                      (set-face-attribute 'mode-line nil :family font :inherit 'variable-pitch)
                      (set-face-attribute 'mode-line-inactive nil :family font :inherit 'variable-pitch)))

    ;; Specify font for all unicode characters
    (cl-loop for font in '("Apple Symbols" "Segoe UI Symbol" "Symbola" "Symbol")
             when (font-available-p font)
             return (set-fontset-font t 'symbol (font-spec :family font) nil 'prepend))

    ;; Specify font for Emoji characters
    (cl-loop for font in '("Noto Color Emoji" "Apple Color Emoji" "Segoe UI Emoji")
             when (font-available-p font)
             return (set-fontset-font t 'emoji (font-spec :family font) nil 'prepend))

    ;; Specify font for Chinese characters
    ;; (cl-loop for font in '("LXGW Neo Xihei" "LXGW WenKai Mono" "WenQuanYi Micro Hei Mono"
    ;;                        "PingFang SC" "Microsoft Yahei UI" "Simhei")
    ;;          when (font-available-p font)
    ;;          return (progn
    ;;                   (setq face-font-rescale-alist `((,font . 1.3)))
    ;;                   (set-fontset-font t 'han (font-spec :family font))))
    ))

(flutter-setup-fonts)
(add-hook 'window-setup-hook #'flutter-setup-fonts)
(add-hook 'server-after-make-frame-hook #'flutter-setup-fonts)
(add-hook 'after-load-theme-hook #'flutter-setup-fonts)

;; Mail
;; (setq message-send-mail-function 'smtpmail-send-it
;;       send-mail-function #'smtpmail-send-it
;;       smtpmail-starttls-credentials '(("smtp.gmail.com" 587 nil nil))
;;       smtpmail-auth-credentials '(("smtp.gmail.com" 587
;;                                    user-mail-address nil))
;;       smtpmail-default-smtp-server "smtp.gmail.com"
;;       smtpmail-smtp-server "smtp.gmail.com"
;;       smtpmail-smtp-service 587)

;; Calendar
;; Set location , then press `S' can show the time of sunrise and sunset
;; (setq calendar-location-name "Chengdu"
;;       calendar-latitude 30.67
;;       calendar-longitude 104.07)

;; Misc.
;; (setq confirm-kill-emacs 'y-or-n-p)
;; (setq package-check-signature nil)
;; (setq trusted-content ':all)

;; Enable proxy
;; (enable-http-proxy)
;; (enable-socks-proxy)

;; Display on the specified monitor
;; (when (and (> (length (display-monitor-attributes-list)) 1)
;;            (> (display-pixel-width) 1920))
;;   (set-frame-parameter nil 'left 288))

;; (put 'cl-destructuring-bind 'lisp-indent-function 'defun)
;; (put 'pdf-view-create-image 'lisp-indent-function 'defun)
;; (put 'treemacs-create-theme 'lisp-indent-function 'defun)

;; For compat
;; (add-hook 'emacs-lisp-mode-hook
;;           (defun compat-add-to-imenu ()
;;             "Add to imenu list."
;;             (add-to-list
;;              'imenu-generic-expression
;;              '(nil
;;                "^\\s-*(\\(compat-def\\(?:un\\|macro\\|alias\\)\\)\\s-+\\(\\(?:\\w\\|\\s_\\|\\\\.\\)+\\)"
;;                2))
;;             (add-to-list
;;              'imenu-generic-expression
;;              '("Packages" "^\\s-*(\\(compat-require\\)\\s-+\\(\\(?:\\w\\|\\s_\\|\\\\.\\)+\\)" 2))
;;             (add-to-list
;;              'imenu-generic-expression
;;              '("Variables"
;;                "^\\s-*(\\(compat-def\\(?:var\\|const\\)\\)?\\s-+\\(\\(?:\\w\\|\\s_\\|\\\\.\\)+\\)[[:space:]\n]+[^)]"
;;                2))))

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;;; custom.el ends here
