;;; init.el --- entry point for Flutter Emacs. -*- lexical-binding: t no-byte-compile: t -*-

;; Flutter Emacs is a fork of Centaur Emacs
;; (https://github.com/seagle0128/.emacs.d, GPL-3.0, copyright Vincent
;; Zhang), re-themed and re-branded, managed inside a Nix flake.
;; See NOTICE.md and vendor/centaur/NOTICE.md for attribution.

;; This file is not part of GNU Emacs.
;;
;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation; either version 3, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;; General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program; see the file COPYING.  If not, write to
;; the Free Software Foundation, Inc., 51 Franklin Street, Fifth
;; Floor, Boston, MA 02110-1301, USA.

;;; Commentary:
;;
;; Structure:
;;   early-init.el            startup perf / frame / transparency
;;   init.el                  this file: bootstraps Elpaca, loads modules
;;   lisp/my-elpaca.el        Elpaca bootstrap + use-package integration
;;   vendor/centaur/lisp/     the absorbed Centaur Emacs modules
;;                            (centaur-* renamed to flutter-*; see
;;                            vendor/centaur/NOTICE.md)
;;   lisp/init-extras.el      QML + media extras carried from the old config
;;   custom.el / custom-post.el(.org)   your personal overrides
;;
;; Packages are installed by Elpaca (lisp/my-elpaca.el), never by Nix —
;; Nix only supplies the emacs binary and external tools.  The theme is
;; `pinaceae' (themes/pinaceae-theme.el), generated by matugen.
;;
;;; Code:

(when (version< emacs-version "28.1")
  (error "This requires Emacs 28.1 and above!"))

;; Speed up Startup Process
;; Optimize `auto-mode-alist'
(setq auto-mode-case-fold nil)

;;
;; Configure Load Path
;;

;; Add "lisp", "vendor/centaur/lisp" and "site-lisp" to the beginning of
;; `load-path'
(defun flutter/update-load-path (&rest _)
  "Prioritize the config's own load paths."
  (dolist (dir '("site-lisp" "lisp" "vendor/centaur/lisp"))
    (push (expand-file-name dir user-emacs-directory) load-path)))

;; Initialize load paths explicitly
(flutter/update-load-path)

;; The `pinaceae' theme lives in this config's themes/ dir (generated
;; by matugen) — make it findable before init-ui.el loads it.
(add-to-list 'custom-theme-load-path
             (expand-file-name "themes" user-emacs-directory))

;; Rescan site-lisp subdirectories after package initialization
(defun flutter/add-subdirs-to-load-path (&rest _)
  "Recursively add subdirectories in `site-lisp' to `load-path'."
  (let ((default-directory (expand-file-name "site-lisp" user-emacs-directory)))
    (normal-top-level-add-subdirs-to-load-path)))

(advice-add #'package-initialize :after #'flutter/add-subdirs-to-load-path)

;; Requisites
(require 'init-const)
(require 'init-custom)
(require 'init-funcs)

;; Packages — Elpaca bootstrap (see lisp/my-elpaca.el).  Must run before
;; any use-package so `:ensure' resolves through Elpaca.
(require 'my-elpaca)

;; use-package setup, custom-file loading, update machinery
(require 'init-package)

;; Preferences
(require 'init-base)
(require 'init-hydra)

(require 'init-ui)
(require 'init-edit)
(require 'init-completion)
(require 'init-snippet)
(require 'init-check)

(require 'init-bookmark)
(require 'init-calendar)
(require 'init-dashboard)
(require 'init-dired)
(require 'init-highlight)
(require 'init-ibuffer)
(require 'init-kill-ring)
(require 'init-workspace)
(require 'init-window)
(require 'init-treemacs)

(require 'init-eshell)
(require 'init-shell)

(require 'init-markdown)
(require 'init-org)
(require 'init-reader)

(require 'init-dict)
(require 'init-docker)
(require 'init-player)
(require 'init-utils)

;; Programming
(require 'init-vc)
(require 'init-lsp)
(require 'init-dap)
(require 'init-ai)

(require 'init-prog)
(require 'init-elisp)
(require 'init-c)
(require 'init-go)
(require 'init-rust)
(require 'init-python)
(require 'init-ruby)
(require 'init-elixir)
(require 'init-web)

;; Flutter extras (QML, media) — loaded last so they can extend
;; anything above
(require 'init-extras)

;;; init.el ends here
